### ISSUE TITLE
Show XP

### ISSUE THREAD

**Issue by jopeek** [jopeek/fvtt-dndbeyond-character-sheet#7]
<@!91969374713311232> Is it possible to to track xp on DNDBeyond character sheet like an exp bar in the original actor sheet or like Obsidian? Would be great if the feature is hidden somewhere and need some toggling in the settings.

**Comment by Noisyink** [comment]
Hi Jopeek,

Wondering if you made any progress on this since May, happy to look into what you would need to add in order to add an experience bar if you don't have the time available to look into it yourself. I prefer your DnDBeyond sheet over others, but have a requirement to use the displayable and editable experience bar that other sheets have.

Thanks

**Comment by Noisyink** [comment]
To add to my previous comment, I've been playing and think I may be close to a fix by using the standard foundry 5e sheet code, mixed with your code, and some slight adjustments.

I'm not very familiar with actually testing things with Foundry yet, but I have created a repo that is almost identical to yours if you would like to take a look at line 74 to 83 of my HTML template, 503 to 514 of my CSS, and 181 to 198 of my JS. Hopefully this can speed up the addition of an experience bar to the sheet.

https://github.com/Noisyink/DnDBeyond-Sheet-Testing

**Comment by jopeek** [comment]
Thanks for this! I'll take a look over the next couple of days. Should be able to implement this relatively soon.

**Comment by jopeek** [comment]
This is implemented in 1.4.0. Didn't need any additional javascript from what I can tell.
